# frozen_string_literal: true

source 'https://rubygems.org'

gem 'puma', '~> 4.3'
gem 'rails', '~> 5.1.6'

gem 'mongoid', '~> 6.0'
gem 'mongoid-rspec'
gem 'mongoid_includes'

gem "nokogiri", ">= 1.10.4"

group :development do
  gem 'byebug'
end

gem 'graphiql-rails', group: :development
gem 'graphql'

gem 'graphoid', path: '../../'
