source 'https://rubygems.org'

gem 'rails', '~> 5.1.6'
gem 'puma', '~> 3.7'

gem 'rspec', group: [:development, :test]
gem 'rspec-rails', group: [:development, :test]

gem 'sqlite3'

gem 'mongoid', '~>6'
gem 'mongoid-compatibility'
gem 'mongoid-rspec'
gem 'mongoid-enum', github: 'outboundworks/mongoid-enum'
gem 'apollo_upload_server', '2.0.0.beta.1'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'


group :development do
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end


gem 'graphql', github: 'rmosolgo/graphql-ruby'
gem 'graphiql-rails', group: :development

gem 'graphoid', path: "../../"
