# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.5'

gem 'puma', '~> 3.7'
gem 'rails', '~> 5.1.6'
gem 'sqlite3'

gem "nokogiri", ">= 1.10.4"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
end

gem 'graphql'
gem 'graphiql-rails', group: :development
gem 'graphoid', path: '../../'
